import turtle

turtle.shape("turtle")
turtle.bgcolor('black')
#black fuckyou
turtle.speed(8)
turtle.pensize(5)
turtle.left(90)
turtle.forward(300)
turtle.right(180)
turtle.forward(600)
turtle.right(90)
turtle.forward(400)
turtle.right(180)
turtle.forward(800)

#0,0 return
turtle.speed(10)
turtle.penup()
turtle.right(180)
turtle.forward(400)
turtle.right(90)
turtle.forward(300)
turtle.right(180)

#red fuckyou
turtle.speed(8)
turtle.pendown()
turtle.color('red')
turtle.right(180)
turtle.forward(300)
turtle.right(180)
turtle.forward(600)
turtle.right(90)
turtle.forward(400)
turtle.right(180)
turtle.forward(800)

#0,0 return
turtle.speed(10)
turtle.penup()
turtle.right(180)
turtle.forward(400)
turtle.right(90)
turtle.forward(300)
turtle.right(180)

#orange fuckyou
turtle.speed(8)
turtle.pendown()
turtle.color('orange')
turtle.right(180)
turtle.forward(300)
turtle.right(180)
turtle.forward(600)
turtle.right(90)
turtle.forward(400)
turtle.right(180)
turtle.forward(800)

#0,0 return
turtle.speed(10)
turtle.penup()
turtle.right(180)
turtle.forward(400)
turtle.right(90)
turtle.forward(300)
turtle.right(180)

#yellow fuckyou
turtle.speed(8)
turtle.pendown()
turtle.color('yellow')
turtle.right(180)
turtle.forward(300)
turtle.right(180)
turtle.forward(600)
turtle.right(90)
turtle.forward(400)
turtle.right(180)
turtle.forward(800)

#0,0 return
turtle.speed(10)
turtle.penup()
turtle.right(180)
turtle.forward(400)
turtle.right(90)
turtle.forward(300)
turtle.right(180)

#green fuckyou
turtle.speed(8)
turtle.pendown()
turtle.color('green')
turtle.right(180)
turtle.forward(300)
turtle.right(180)
turtle.forward(600)
turtle.right(90)
turtle.forward(400)
turtle.right(180)
turtle.forward(800)

#0,0 return
turtle.speed(10)
turtle.penup()
turtle.right(180)
turtle.forward(400)
turtle.right(90)
turtle.forward(300)
turtle.right(180)

#blue fuckyou
turtle.speed(8)
turtle.pendown()
turtle.color('blue')
turtle.right(180)
turtle.forward(300)
turtle.right(180)
turtle.forward(600)
turtle.right(90)
turtle.forward(400)
turtle.right(180)
turtle.forward(800)

#0,0 return
turtle.speed(10)
turtle.penup()
turtle.right(180)
turtle.forward(400)
turtle.right(90)
turtle.forward(300)
turtle.right(180)

#cyan fuckyou
turtle.speed(8)
turtle.pendown()
turtle.color('cyan')
turtle.right(180)
turtle.forward(300)
turtle.right(180)
turtle.forward(600)
turtle.right(90)
turtle.forward(400)
turtle.right(180)
turtle.forward(800)

#0,0 return
turtle.speed(10)
turtle.penup()
turtle.right(180)
turtle.forward(400)
turtle.right(90)
turtle.forward(300)
turtle.right(180)

#purple fuckyou
turtle.speed(8)
turtle.pendown()
turtle.color('purple')
turtle.right(180)
turtle.forward(300)
turtle.right(180)
turtle.forward(600)
turtle.right(90)
turtle.forward(400)
turtle.right(180)
turtle.forward(800)

#0,0 return
turtle.speed(10)
turtle.penup()
turtle.right(180)
turtle.forward(400)
turtle.right(90)
turtle.forward(300)
turtle.right(180)

#black fuckyou
turtle.speed(8)
turtle.pendown()
turtle.color('black')
turtle.right(180)
turtle.forward(300)
turtle.right(180)
turtle.forward(600)
turtle.right(90)
turtle.forward(400)
turtle.right(180)
turtle.forward(800)

#colorful
#0,0 return
turtle.speed(10)
turtle.penup()
turtle.right(180)
turtle.forward(400)
turtle.right(90)
turtle.forward(300)
turtle.right(180)

#while test=fail
turtle.bgcolor('white')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

turtle.bgcolor('red')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

turtle.bgcolor('orange')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

turtle.bgcolor('green')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

turtle.bgcolor('blue')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

turtle.bgcolor('cyan')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

turtle.bgcolor('purple')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

#2
turtle.bgcolor('white')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

turtle.bgcolor('red')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

turtle.bgcolor('orange')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

turtle.bgcolor('green')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

turtle.bgcolor('blue')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

turtle.bgcolor('cyan')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

turtle.bgcolor('purple')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

#3
turtle.bgcolor('white')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

turtle.bgcolor('red')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

turtle.bgcolor('orange')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

turtle.bgcolor('green')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

turtle.bgcolor('blue')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

turtle.bgcolor('cyan')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

turtle.bgcolor('purple')
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)
turtle.right(60)

#fin
turtle.bgcolor('black')
turtle.right(60)
turtle.right(60)
turtle.bgcolor('white')
turtle.right(60)
turtle.right(60)
turtle.bgcolor('black')
turtle.right(60)
turtle.right(60)
turtle.bgcolor('white')
turtle.right(60)
turtle.right(60)
turtle.bgcolor('black')
turtle.right(60)
turtle.right(60)
turtle.bgcolor('white')
turtle.right(60)
turtle.right(60)
turtle.bgcolor('black')
turtle.right(60)
turtle.right(60)
turtle.bgcolor('white')
turtle.right(60)
turtle.right(60)
turtle.bgcolor('black')
turtle.right(60)
turtle.right(60)
turtle.bgcolor('white')
turtle.right(60)
turtle.right(60)
turtle.bgcolor('black')
turtle.right(60)
turtle.right(60)
turtle.bgcolor('white')
turtle.right(60)
turtle.right(60)
turtle.bgcolor('black')
turtle.right(60)
turtle.right(60)

turtle.exitonclick()